version: "3"

services:
  # ================================= Bot =====================================
  # Generic Rasa bot, used to run console for example.
  rasa-server:
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    depends_on:
      - actions
    networks: 
      - production
    # public: true
    restart: unless-stopped
    ports:
      - '5005:8081'
    command: bash -c "rm -rf models/* && rasa train && rasa run --enable-api --cors \"*\" -p 8081"
  # ================================= Actions =================================
  # Rasa middleware used to connect with external APIs.
  actions:
    build:
      context: .
      dockerfile: ./docker/actions.Dockerfile
    ports:
      - 5055:5055
    networks:
      - production
  # ================================= Website =================================
  # Simple website with Rasa chat widget.
  web:
    build:
      context: . 
      dockerfile: ./docker/web.Dockerfile
    ports:
      - 3000:3000
    networks:
      - production
    depends_on:
      - rasa-server
      - actions

networks: 
    production:
        driver: bridge